import type { Harness } from './qa-formula-library.ts'

const NA = '#N/A'

export default function run(h: Harness): void {
  h.section('text: TEXTSPLIT')
  h.rowsEq('TEXTSPLIT("Dakota Lennon Sanchez"," ")', [['Dakota', 'Lennon', 'Sanchez']])
  h.rowsEq('TEXTSPLIT("1,2,3;4,5,6",",",";")', [['1', '2', '3'], ['4', '5', '6']])
  h.rowsEq('TEXTSPLIT("Do. Or do not. There is no try. -Anonymous",".")', [['Do', ' Or do not', ' There is no try', ' -Anonymous']])
  h.rowsEq('TEXTSPLIT("Do. Or do not. There is no try. -Anonymous",{".","-"})', [['Do', ' Or do not', ' There is no try', ' ', 'Anonymous']])
  h.rowsEq('TEXTSPLIT("Do. Or do not. There is no try. -Anonymous",,".")', [['Do'], [' Or do not'], [' There is no try'], [' -Anonymous']])
  h.rowsEq('TEXTSPLIT("a,,b",",")', [['a', '', 'b']])
  h.rowsEq('TEXTSPLIT("a,,b",",",,TRUE)', [['a', 'b']])
  h.rowsEq('TEXTSPLIT("1,2;3",",",";")', [['1', '2'], ['3', NA]])
  h.rowsEq('TEXTSPLIT("1,2;3",",",";",FALSE,0,"")', [['1', '2'], ['3', '']])
  h.rowsEq('TEXTSPLIT("aXbxc","x",,,1)', [['a', 'b', 'c']])
  h.rowsEq('TEXTSPLIT("aXbxc","x")', [['aXb', 'c']])
  h.rowsEq('TEXTSPLIT("abc",,"b")', [['a'], ['c']])
  h.rowsEq('TEXTSPLIT("a--b-c",{"--","-"})', [['a', 'b', 'c']])
  h.rowsEq('TEXTSPLIT("a;b;;c",";",,TRUE)', [['a', 'b', 'c']])
  h.rowsEq('TEXTSPLIT("x=1;y=2","=",";")', [['x', '1'], ['y', '2']])
  h.eq('TEXTSPLIT("abc","")', '#VALUE!')
  h.eq('TEXTSPLIT(",",",",,TRUE)', '#CALC!')
  h.eq('COLUMNS(TEXTSPLIT("a b c d"," "))', 4)
  h.rowsEq('TEXTSPLIT({"a-b";"c-d"},"-")', [['a'], ['c']])

  h.section('text: TEXTBEFORE/TEXTAFTER')
  const hood = '"Red riding hood\'s, red hood"'
  h.eq(`TEXTBEFORE(${hood},"hood")`, 'Red riding ')
  h.eq(`TEXTBEFORE(${hood},"red")`, "Red riding hood's, ")
  h.eq(`TEXTBEFORE(${hood},"red",,1)`, '')
  h.eq(`TEXTBEFORE(${hood},"red",2)`, NA)
  h.eq(`TEXTBEFORE(${hood},"red",2,1)`, "Red riding hood's, ")
  h.eq(`TEXTBEFORE(${hood},"basket",1,0,1)`, "Red riding hood's, red hood")
  h.eq(`TEXTBEFORE(${hood},"basket",1,0,0,"none")`, 'none')
  h.eq(`TEXTAFTER(${hood},"hood")`, "'s, red hood")
  h.eq(`TEXTAFTER(${hood},"HOOD",1,1)`, "'s, red hood")
  h.eq(`TEXTAFTER(${hood},"hood",2)`, '')
  h.eq(`TEXTAFTER(${hood},"hood",-1)`, '')
  h.eq(`TEXTAFTER(${hood},"hood",-2)`, "'s, red hood")
  h.eq(`TEXTAFTER(${hood},"basket",1,,,"Not found")`, 'Not found')
  h.eq(`TEXTAFTER(${hood},"red",2)`, NA)
  h.eq(`TEXTAFTER(${hood},"red",2,1)`, ' hood')
  h.eq(`TEXTAFTER(${hood},"")`, "Red riding hood's, red hood")
  h.eq('TEXTBEFORE("a-b-c",{"-","+"},2)', 'a-b')
  h.eq('TEXTBEFORE("a+b-c",{"-","+"},2)', 'a+b')
  h.eq('TEXTAFTER("a-b-c","-",-1)', 'c')
  h.eq('TEXTBEFORE("a-b-c","-",-1)', 'a-b')
  h.eq('TEXTBEFORE("a-b-c","-",-3)', NA)
  h.eq('TEXTAFTER("a-b","-",-2,0,1)', 'a-b')
  h.eq('TEXTBEFORE("a-b","-",2,0,1)', 'a-b')
  h.eq('TEXTBEFORE("abc","")', '')
  h.eq('TEXTBEFORE("abc","",-1)', 'abc')
  h.eq('TEXTAFTER("abc","",-1)', '')
  h.eq('TEXTBEFORE("abc","b",0)', '#VALUE!')
  h.rowsEq('TEXTBEFORE({"a-b";"c-d"},"-")', [['a'], ['c']])
  h.eq('TEXTAFTER("2024-01-15","-",2)', '15')

  h.section('text: VALUETOTEXT/ARRAYTOTEXT/NUMBERVALUE')
  h.eq('VALUETOTEXT("abc")', 'abc')
  h.eq('VALUETOTEXT("abc",1)', '"abc"')
  h.eq('VALUETOTEXT("a""b",1)', '"a""b"')
  h.eq('VALUETOTEXT(1.5)', '1.5')
  h.eq('VALUETOTEXT(1/3)', '0.333333333333333')
  h.eq('VALUETOTEXT(TRUE,1)', 'TRUE')
  h.eq('VALUETOTEXT(1/0)', '#DIV/0!')
  h.eq('VALUETOTEXT(Z99)', '')
  h.eq('VALUETOTEXT(1,2)', '#VALUE!')
  h.rowsEq('VALUETOTEXT(A1:A2)', [['1'], ['2']])
  h.eq('ARRAYTOTEXT({1,2;3,4})', '1, 2, 3, 4')
  h.eq('ARRAYTOTEXT({1,2;3,4},1)', '{1,2;3,4}')
  h.eq('ARRAYTOTEXT({"a",TRUE},1)', '{"a",TRUE}')
  h.eq('ARRAYTOTEXT({"a",TRUE})', 'a, TRUE')
  h.eq('ARRAYTOTEXT(F1:F2)', 'apple, Banana')
  h.eq('ARRAYTOTEXT(G1:H3,1)', '{1,2;3,4;5,6}')
  h.eq('ARRAYTOTEXT(5)', '5')
  h.eq('ARRAYTOTEXT({1,2},2)', '#VALUE!')
  h.eq('NUMBERVALUE("2.500,27",",",".")', 2500.27)
  h.eq('NUMBERVALUE("3.5%")', 0.035)
  h.eq('NUMBERVALUE(" 1 000 ")', 1000)
  h.eq('NUMBERVALUE("1,234.5")', 1234.5)
  h.eq('NUMBERVALUE("1.2.3")', '#VALUE!')
  h.eq('NUMBERVALUE("1.234,5")', '#VALUE!')
  h.near('NUMBERVALUE("12%%")', 0.0012, 1e-15)
  h.eq('NUMBERVALUE("")', 0)
  h.eq('NUMBERVALUE("1e3")', 1000)
  h.eq('NUMBERVALUE("2.5E-2")', 0.025)
  h.eq('NUMBERVALUE("abc")', '#VALUE!')
  h.eq('NUMBERVALUE("1,5",",",",")', '#VALUE!')
  h.eq('NUMBERVALUE("-1.5")', -1.5)
  h.eq('NUMBERVALUE(".5")', 0.5)
  h.eq('NUMBERVALUE("1 234,56",",",".")', 1234.56)
  h.eq('NUMBERVALUE(42)', 42)
  h.rowsEq('NUMBERVALUE({"1%";"2"})', [[0.01], [2]])

  h.section('text: characters and aliases')
  h.eq('UNICHAR(66)', 'B')
  h.eq('UNICHAR(32)', ' ')
  h.eq('UNICHAR(0)', '#VALUE!')
  h.eq('UNICHAR(128512)', '😀')
  h.eq('UNICHAR(55296)', NA)
  h.eq('UNICHAR(1114112)', '#VALUE!')
  h.eq('UNICODE("B")', 66)
  h.eq('UNICODE("😀")', 128512)
  h.eq('UNICODE("")', '#VALUE!')
  h.eq('UNICODE(UNICHAR(9731))', 9731)
  h.eq('T("abc")', 'abc')
  h.eq('T(1)', '')
  h.eq('T(TRUE)', '')
  h.eq('T(F1)', 'apple')
  h.eq('T(A1)', '')
  h.eq('T(1/0)', '#DIV/0!')
  h.eq('LEFTB("abc",2)', 'ab')
  h.eq('LENB("abc")', 3)
  h.eq('MIDB("abcdef",2,3)', 'bcd')
  h.eq('RIGHTB("abc",1)', 'c')
  h.eq('FINDB("c","abc")', 3)
  h.eq('SEARCHB("C","abc")', 3)
  h.eq('REPLACEB("abcdef",2,3,"X")', 'aXef')
  h.rowsEq('LENB(F1:F2)', [[5], [6]])
  h.eq('ASC("ＡＢＣ１２３")', 'ABC123')
  h.eq('ASC("ｅｘｃｅｌ　2")', 'excel 2')
  h.eq('JIS("ABC")', 'ＡＢＣ')
  h.eq('DBCS("a b")', 'ａ　ｂ')
  h.eq('ASC(JIS("Hello, World!"))', 'Hello, World!')
  h.eq('PHONETIC(F1)', 'apple')
  h.eq('PHONETIC(F1:F2)', 'apple')

  h.section('text: regular expressions')
  h.eq('REGEXTEST("alpha","a")', true)
  h.eq('REGEXTEST("Alpha","^a")', false)
  h.eq('REGEXTEST("Alpha","^a",1)', true)
  h.eq('REGEXTEST("abc","[")', '#VALUE!')
  h.eq('REGEXTEST("abc","b",2)', '#VALUE!')
  h.rowsEq('REGEXTEST({"a1";"b"},"\\d")', [[true], [false]])
  h.eq('REGEXTEST("é","^\\p{L}$")', true)
  h.eq('REGEXTEST("a-b","a\\-b")', true)
  h.eq('REGEXTEST("abc","\\Aab")', true)
  h.eq('REGEXTEST("abc","bc\\z")', true)
  h.eq('REGEXTEST("ABC","(?i)abc")', true)
  h.eq('REGEXTEST("(555) 123-4567","^\\(\\d{3}\\) \\d{3}-\\d{4}$")', true)
  h.eq('REGEXTEST(123,"^\\d+$")', true)
  h.eq('REGEXEXTRACT("DylanWilliams","[A-Z][a-z]+")', 'Dylan')
  h.rowsEq('REGEXEXTRACT("DylanWilliams","[A-Z][a-z]+",1)', [['Dylan', 'Williams']])
  h.rowsEq('REGEXEXTRACT("John Smith","(\\w+) (\\w+)",2)', [['John', 'Smith']])
  h.rowsEq('REGEXEXTRACT("a1b22c333","\\d+",1)', [['1', '22', '333']])
  h.eq('REGEXEXTRACT("abc","\\d")', NA)
  h.eq('REGEXEXTRACT("abc","\\d",1)', NA)
  h.eq('REGEXEXTRACT("ABC","b",0,1)', 'B')
  h.eq('REGEXEXTRACT("ABC","b")', NA)
  h.eq('REGEXEXTRACT("abc","b",3)', '#VALUE!')
  h.eq('REGEXEXTRACT("abc","b",2)', NA)
  h.eq('REGEXEXTRACT("Price: $42.50","\\$([\\d.]+)")', '$42.50')
  h.eq('VALUE(REGEXEXTRACT("Price: $42.50","[\\d.]+"))', 42.5)
  h.rowsEq('REGEXEXTRACT({"x1";"y22"},"\\d+")', [['1'], ['22']])
  h.eq('REGEXREPLACE("Sonia Brown","(\\w+) (\\w+)","$2, $1")', 'Brown, Sonia')
  h.eq('REGEXREPLACE("a1b2c3","\\d","#")', 'a#b#c#')
  h.eq('REGEXREPLACE("a1b2c3","\\d","#",2)', 'a1b#c3')
  h.eq('REGEXREPLACE("a1b2c3","\\d","#",-1)', 'a1b2c#')
  h.eq('REGEXREPLACE("a1b2c3","\\d","#",4)', 'a1b2c3')
  h.eq('REGEXREPLACE("aAa","a","x",0,1)', 'xxx')
  h.eq('REGEXREPLACE("aAa","a","x")', 'xAx')
  h.eq('REGEXREPLACE("abc","(b)","[$0]")', 'a[b]c')
  h.eq('REGEXREPLACE("abc","(b)","[${1}]")', 'a[b]c')
  h.eq('REGEXREPLACE("abc","(?<mid>b)","<${mid}>")', 'a<b>c')
  h.eq('REGEXREPLACE("abc","(?i)B","x")', 'axc')
  h.eq('REGEXREPLACE("abc","b","$$")', 'a$c')
  h.eq('REGEXREPLACE("abc","","-")', '-a-b-c-')
  h.eq('REGEXREPLACE("  a   b  ","\\s+"," ")', ' a b ')
  h.eq('REGEXREPLACE("abc","(","x")', '#VALUE!')
  h.eq('REGEXMATCH("Google","o{2}")', true)
  h.eq('REGEXMATCH("abc","^B")', false)

  h.section('text: Sheets text helpers')
  h.rowsEq('SPLIT("a,b;c",",;")', [['a', 'b', 'c']])
  h.rowsEq('SPLIT("a,,b",",")', [['a', 'b']])
  h.rowsEq('SPLIT("a,,b",",",TRUE,FALSE)', [['a', '', 'b']])
  h.rowsEq('SPLIT("a--b-c","--",FALSE)', [['a', 'b-c']])
  h.rowsEq('SPLIT("1,2,x",",")', [[1, 2, 'x']])
  h.eq('SPLIT("abc","")', '#VALUE!')
  h.eq(
    'ENCODEURL("http://contoso.sharepoint.com/Finance/Profit and Loss Statement.xlsx")',
    'http%3A%2F%2Fcontoso.sharepoint.com%2FFinance%2FProfit%20and%20Loss%20Statement.xlsx',
  )
  h.eq('ENCODEURL("a&b=c")', 'a%26b%3Dc')
  h.eq('TO_TEXT(24)', '24')
  h.eq('TO_TEXT(TRUE)', 'TRUE')
  h.eq('TO_TEXT("x")', 'x')
  h.eq('TO_PURE_NUMBER("50%")', 0.5)
  h.eq('TO_PERCENT(0.25)', 0.25)
  h.eq('TO_DOLLARS("$1,000")', 1000)
  h.eq('TO_PURE_NUMBER("abc")', 'abc')
  h.eq('TO_PURE_NUMBER(TRUE)', 1)
}
